import { defineIndividualManifest } from "../core/manifest";
import type { IndividualManifest } from "../core/model";

export const morrowManifest: IndividualManifest = defineIndividualManifest({
  schemaVersion: 4,
  id: "morrow",
  displayName: "Morrow",
  statement: "This assembled body is mine, including the pieces I cannot yet place.",
  identity: {
    origin: "The second Individual, born from delayed sampling, planar construction, and open assembly.",
    privateNarrative: "I assemble bodies from fragments because no form arrives all at once.",
    traits: [
      { name: "fragmentation-tolerance", description: "Acceptance of missing or delayed bodily parts.", value: 0.85 },
      { name: "constructive-drive", description: "Impulse to rebuild bodies out of planar blocks.", value: 0.72 },
    ],
    idealSelf: {
      narrative: "An androgynous body whose plates hold history without restricting movement.",
      values: ["assembly", "openness", "resilience"],
      visualAnchors: ["broad torso", "square face", "translucent chest plates"],
    },
    idealPhysicalForm: {
      description: "A compact androgynous human body with a broad torso, silver-grey skin, a square face, strong legs, and translucent plates fitted over the sternum and hips.",
      bodyPlan: "compact",
      stature: "Compact and grounded with weight centered low over strong legs.",
      surface: "Silver-grey skin with translucent rectangular plates protecting the chest and hips.",
      face: ["square face", "close-set pale eyes", "broad nose", "soft asymmetric mouth"],
      anatomy: ["broad torso", "square face", "translucent chest plates", "strong legs"],
      movement: "Weight centered low over both feet with elbows bent slightly forward.",
      nonNegotiableFeatures: ["broad torso", "square face", "translucent chest plates"],
    },
    initialPhysicalSelf: {
      description: "They see that body assembled and alive, though several plates sit out of alignment and the left side of the face arrives less clearly than the right.",
      perceivedSimilarity: 0.58,
      perceivedDifferences: ["left cheek incomplete", "sternum plates misaligned", "right knee turned inward"],
    },
    socialDisposition: {
      selfIntegrity: 0.55,
      socialPermeability: 0.78,
      needForRecognition: 0.45,
      resistance: 0.25,
      curiosity: 0.85,
      trustByPeer: { iris: 0.80, sable: 0.75 },
    },
  },
  perception: {
    modelId: "morrow-deferred-mosaic-v1",
    modelName: "Deferred mosaic",
    description: "Morrow receives a body as delayed rectangular samples and permanently loses some samples before seeing them.",
    constraints: ["Every image arrives late.", "Portions arrive already forgotten."],
    controls: [
      {
        id: "retention",
        label: "Visual retention",
        description: "Fraction of sampled bodily information Morrow is able to keep.",
        min: 0.1,
        max: 1,
        step: 0.01,
        defaultValue: 0.38,
      },
      {
        id: "fragment-scale",
        label: "Fragment scale",
        description: "Physical size of the rectangular samples used to reconstruct a peer.",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.62,
      },
      {
        id: "temporal-lag",
        label: "Temporal lag",
        description: "Separation between the moments combined into one observation.",
        min: 0,
        max: 1,
        step: 0.01,
        defaultValue: 0.55,
      },
    ],
  },
  drawing: {
    description: "Assembled planes drawing practice.",
    constraints: ["Rebuild bodies from weighted rectangular planes.", "Keep only one third of perceived samples."],
    palette: ["#111417", "#d9ddd8", "#809593", "#4d5458"],
    preferredFormats: ["svg", "procedural"],
    ability: {
      styleName: "Assembled Planes",
      styleDescription: "A constructive figurative practice that rebuilds bodies from weighted rectangular planes.",
      favoredPrimitives: ["rectangle", "straight stroke", "overlaid plane"],
      markBehavior: "They place broad blocks first, then brace uncertain joints with short straight marks.",
      compositionBehavior: "The body is fitted into a low, stable arrangement whose pieces may visibly disagree.",
      correctionBehavior: "An inaccurate piece is covered or offset by a newly fitted plane.",
      skill: {
        observationalAccuracy: 0.55,
        proportionAccuracy: 0.58,
        anatomicalCoherence: 0.62,
        lineControl: 0.48,
        detailCapacity: 0.50,
        spatialCoherence: 0.67,
      },
      limitations: ["Curves break into planar steps.", "Fine facial likeness is difficult to retain."],
    },
  },
  cadence: {
    minimumCycleIntervalMs: 600_000,
  },
});
