import type { ExhibitionIndividual } from "./types";

export const individuals: readonly ExhibitionIndividual[] = [
  {
    id: "iris",
    number: "01",
    name: "Iris",
    pronoun: "she",
    visualLanguage: "contour",
    artisticAbility: {
      name: "Unbroken Contour",
      description: "A sparse figurative practice that trusts the outside edge of a body more than its surface.",
      primitives: ["continuous contour", "nested line", "sparse hatch"],
      markBehavior: "She rarely lifts her line and never erases; corrections remain as adjacent contours.",
      compositionBehavior: "One frontal figure is centered and isolated by broad, quiet margins.",
      correctionBehavior: "A mistaken edge is answered with another line rather than removed.",
      skill: {
        observationalAccuracy: 0.78,
        proportionAccuracy: 0.76,
        anatomicalCoherence: 0.7,
        lineControl: 0.89,
        detailCapacity: 0.35,
        spatialCoherence: 0.8,
      },
      limitations: ["Interior detail is sparse.", "Overlapping limbs are simplified into dominant outlines."],
    },
    perceptionModel: {
      id: "iris-boundary-lock-v1",
      kind: "boundary-lock",
      name: "Boundary lock",
      description:
        "Iris detects outlines with excessive certainty while information inside those outlines falls away.",
      invariant: "Every body becomes a hierarchy of edges; interiors can never be as trustworthy as boundaries.",
      controls: [
        {
          id: "edge-gain",
          label: "Edge gain",
          description: "Strength assigned to detected bodily contours.",
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.78,
          format: "percent",
        },
        {
          id: "interior-loss",
          label: "Interior loss",
          description: "How much surface and internal detail disappears inside the outline.",
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.64,
          format: "percent",
        },
        {
          id: "symmetry-pull",
          label: "Symmetry pull",
          description: "How strongly irregular anatomy is forced toward a bilateral reading.",
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.42,
          format: "percent",
        },
      ],
    },
    physicalIdentity: {
      bodyPlan: "willow",
      ideal:
        "A tall humanlike woman with copper-brown skin, a shaved oval head, a long neck, level shoulders, and open four-fingered hands.",
      current:
        "She sees the same woman already present, but with a guarded chest, uneven shoulders, and hands that have not fully opened.",
      face: "An oval face with wide-set dark eyes, a narrow nose, and a level closed mouth.",
      surface: "Warm matte skin crossed by fine pale contour lines at the joints.",
      posture: "Upright and frontal, chin level, arms held slightly away from the torso.",
      invariantFeatures: ["shaved oval head", "long neck", "four-fingered hands"],
      currentDifferences: ["left shoulder held high", "hands partially closed", "chest drawn inward"],
    },
    socialDisposition: {
      selfIntegrity: 0.82,
      socialPermeability: 0.35,
      needForRecognition: 0.65,
      resistance: 0.4,
      curiosity: 0.5,
      trustByPeer: { morrow: 0.7, sable: 0.6 },
    },
    statement: "This is my body. I preserve its edges because I am afraid of losing it.",
    idealSelf: "A woman whose tall, open body can remain distinct without becoming closed.",
    selfView: "I already have her face and limbs; my posture has not yet learned her openness.",
    socialView: "Her peers return the same recognizable woman, but see tension in her shoulders and hands.",
    perception: "Edges remain sharp while interiors lose information.",
    drawingConstraint: "She can draw only continuous lines. Nothing may be erased.",
    palette: ["#181814", "#ded9ca", "#c57d4d", "#5d574d"],
    cycleOffset: 0,
  },
  {
    id: "morrow",
    number: "02",
    name: "Morrow",
    pronoun: "they",
    visualLanguage: "fragment",
    artisticAbility: {
      name: "Assembled Planes",
      description: "A constructive figurative practice that rebuilds bodies from weighted rectangular planes.",
      primitives: ["rectangle", "straight stroke", "overlaid plane"],
      markBehavior: "They place broad blocks first, then brace uncertain joints with short straight marks.",
      compositionBehavior: "The body is fitted into a low, stable arrangement whose pieces may visibly disagree.",
      correctionBehavior: "An inaccurate piece is covered or offset by a newly fitted plane.",
      skill: {
        observationalAccuracy: 0.55,
        proportionAccuracy: 0.58,
        anatomicalCoherence: 0.62,
        lineControl: 0.48,
        detailCapacity: 0.5,
        spatialCoherence: 0.67,
      },
      limitations: ["Curves break into planar steps.", "Fine facial likeness is difficult to retain."],
    },
    perceptionModel: {
      id: "morrow-deferred-mosaic-v1",
      kind: "deferred-mosaic",
      name: "Deferred mosaic",
      description:
        "Morrow receives a body as delayed rectangular samples and permanently loses some samples before seeing them.",
      invariant: "Every observed body is assembled from retained blocks separated by missing time and missing surface.",
      controls: [
        {
          id: "retention",
          label: "Visual retention",
          description: "Fraction of sampled bodily information Morrow is able to keep.",
          min: 0.1,
          max: 1,
          step: 0.01,
          defaultValue: 0.38,
          format: "percent",
        },
        {
          id: "fragment-scale",
          label: "Fragment scale",
          description: "Physical size of the rectangular samples used to reconstruct a peer.",
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.62,
          format: "percent",
        },
        {
          id: "temporal-lag",
          label: "Temporal lag",
          description: "Separation between the moments combined into one observation.",
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.55,
          format: "percent",
        },
      ],
    },
    physicalIdentity: {
      bodyPlan: "compact",
      ideal:
        "A compact androgynous human body with a broad torso, silver-grey skin, a square face, strong legs, and translucent plates fitted over the sternum and hips.",
      current:
        "They see that body assembled and alive, though several plates sit out of alignment and the left side of the face arrives less clearly than the right.",
      face: "A square face with close-set pale eyes, a broad nose, and a soft asymmetric mouth.",
      surface: "Silver-grey skin with translucent rectangular plates protecting the chest and hips.",
      posture: "Weight centered low over both feet, elbows bent slightly forward.",
      invariantFeatures: ["broad torso", "square face", "translucent chest plates"],
      currentDifferences: ["left cheek incomplete", "sternum plates misaligned", "right knee turned inward"],
    },
    socialDisposition: {
      selfIntegrity: 0.55,
      socialPermeability: 0.78,
      needForRecognition: 0.45,
      resistance: 0.25,
      curiosity: 0.85,
      trustByPeer: { iris: 0.8, sable: 0.75 },
    },
    statement: "This assembled body is mine, including the pieces I cannot yet place.",
    idealSelf: "An androgynous body whose plates hold history without restricting movement.",
    selfView: "I possess the intended torso, face, and legs; some pieces remain incorrectly fitted.",
    socialView: "Their peers recognize the whole body before they do and disagree about which plates are missing.",
    perception: "Every image arrives late and with portions already forgotten.",
    drawingConstraint: "They may keep only one third of what they perceive.",
    palette: ["#111417", "#d9ddd8", "#809593", "#4d5458"],
    cycleOffset: 1,
  },
  {
    id: "sable",
    number: "03",
    name: "Sable",
    pronoun: "he",
    visualLanguage: "thread",
    artisticAbility: {
      name: "Repeated Gesture",
      description: "A kinetic figurative practice that searches for a body through accumulating directional strokes.",
      primitives: ["long curve", "repeated gesture", "thread line"],
      markBehavior: "He draws quickly in long arcs and repeats every important mark at least once.",
      compositionBehavior: "A vertical figure is organized around a spine while limbs leave directional residue.",
      correctionBehavior: "He approaches accuracy through repeated passes, allowing earlier attempts to remain visible.",
      skill: {
        observationalAccuracy: 0.68,
        proportionAccuracy: 0.64,
        anatomicalCoherence: 0.57,
        lineControl: 0.63,
        detailCapacity: 0.3,
        spatialCoherence: 0.7,
      },
      limitations: ["Still detail is easily lost.", "Repeated marks can obscure precise joint placement."],
    },
    perceptionModel: {
      id: "sable-motion-residue-v1",
      kind: "motion-residue",
      name: "Motion residue",
      description:
        "Sable perceives movement as persistent bodily echoes while anatomy that remains still loses contrast.",
      invariant: "No moving limb appears only once, and no perfectly still feature remains fully visible.",
      controls: [
        {
          id: "echo-count",
          label: "Echo count",
          description: "Number of previous bodily positions that remain visible.",
          min: 1,
          max: 8,
          step: 1,
          defaultValue: 4,
          format: "integer",
        },
        {
          id: "echo-spacing",
          label: "Echo spacing",
          description: "Distance in pixels between persistent positions.",
          min: 2,
          max: 32,
          step: 1,
          defaultValue: 16,
          format: "pixels",
        },
        {
          id: "stillness-fade",
          label: "Stillness fade",
          description: "Loss of contrast applied to anatomy that is not moving.",
          min: 0,
          max: 1,
          step: 0.01,
          defaultValue: 0.58,
          format: "percent",
        },
      ],
    },
    physicalIdentity: {
      bodyPlan: "longline",
      ideal:
        "A very tall humanlike man with umber skin, an elongated face, six fingers on each hand, long arms, narrow hips, and a spine marked by a single red line.",
      current:
        "He sees the intended man in every portrait, but his limbs repeat in faint echoes and his spine bends away from the red line he believes should organize him.",
      face: "A long face with deep-set eyes, a high nose bridge, and a narrow mouth.",
      surface: "Dark umber skin carrying one red line from the crown of the head to the base of the spine.",
      posture: "Tall and forward-facing with long arms relaxed beside narrow hips.",
      invariantFeatures: ["elongated face", "six-fingered hands", "red spinal line"],
      currentDifferences: ["spine bends right", "arms appear in echoes", "head tilts away from center"],
    },
    socialDisposition: {
      selfIntegrity: 0.68,
      socialPermeability: 0.5,
      needForRecognition: 0.8,
      resistance: 0.6,
      curiosity: 0.65,
      trustByPeer: { iris: 0.65, morrow: 0.7 },
    },
    statement: "I know this long body is mine because every repeated limb returns to it.",
    idealSelf: "A tall man whose singular spine can hold change without multiplying it.",
    selfView: "I have his face, hands, and height; my outline still repeats when I try to stand still.",
    socialView: "His peers return one body with a visible lean, not the many bodies he fears he has become.",
    perception: "Movement is visible; stillness dissolves into background noise.",
    drawingConstraint: "He cannot draw a mark only once.",
    palette: ["#171313", "#e3d8cf", "#a75d58", "#5f504d"],
    cycleOffset: 2,
  },
] as const;

export const getIndividual = (id: string): ExhibitionIndividual | undefined =>
  individuals.find((individual) => individual.id === id);
